version: '3'
# All 3 serrvices are on same network named 'example', enabling container communication.
# MY SQL Database is set to have host name as `sqldb`, with no ports exposed to host.
# PHPMyAdmin communicates with `sqldb` over default port `3306` using the same user name, password declared in environemnt section of sqldb.
# PHPMyAdmin exposes UI over 8080 port on host for our use.
# Flaskapp which is built from docker file in run time, exposes port 4444 of container to 4444 of host by default unless changed. 
# Any change to Flask app service must be followed by respective change in config.json which app reads and depends on for configuration.   
services:
  sqldb:
    image: mysql
    restart: always
    container_name: mysql
    volumes:
      - sqlvol:/var/lib/mysql
    networks:
      app:
        aliases: 
          - ${MYSQL_HOST}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  pma:
    image: phpmyadmin
    restart: always
    container_name: pma
    depends_on:
      - sqldb
    networks:
      app:
        aliases:
          - pma
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=3306
      - PMA_HOST=${MYSQL_HOST}
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqldb
    restart: always
    container_name: FlaskApp
    ports:
      - 4444:4444
    networks:
      app:

networks:
  app:
volumes:
  sqlvol:
    driver: local
